
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create index tex
      run: | 
        cp main.tex index.tex 
    - uses: actions/checkout@v1
    - name: Run make4ht
      # uses: michal-h21/make4ht-action@master
      uses: docker://ghcr.io/michal-h21/make4ht-action:latest
      env:
        command: 'make4ht -c config.cfg -ua debug -d out main.tex "fn-in"'
    - name: Publish the web pages
      uses:  peaceiris/actions-gh-pages@v3
      with:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PUBLISH_BRANCH: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
